spring:
  application:
    name: talentflow-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/talentflow
    username: root
    password: Vinitha@1245
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hour in milliseconds